# declare google test source code location

# declare dependencies
INCLUDE = -I/Users/MorehouseJ09/Documents/programs/cpp/cpp_boilerplate/include

 
LIBRARIES =
PACKAGES = jansson

# compilar options
COMPILER = g++
COMPILERFLAGS = -O3 $(INCLUDE) $(pkg-config --libs --cflags $(PACKAGES))

# output
PROGRAM = current
SOURCE = *.cpp modules/*.cpp classes/*.cpp

